/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'export', // Required for GitHub Pages hosting
  images: {
    unoptimized: true, // GitHub Pages doesn't support Next.js default image optimization
  },
};
module.exports = nextConfig;